include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - android/**

linter:
  rules:
    avoid_multiple_declarations_per_line: false
    document_ignores: false
    implicit_call_tearoffs: false
    prefer_expression_function_bodies: true
    public_member_api_docs: false
    sort_pub_dependencies: false
