name: Analyze
on:
  push:
    branches-ignore:
      - main
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: 'stable'
      - run: flutter analyze
      - run: flutter pub run dart_code_metrics:metrics analyze lib
      - run: flutter pub run dart_code_metrics:metrics check-unused-files lib
      #- run: flutter pub run dart_code_metrics:metrics check-unused-code lib
      - run: flutter format -n --set-exit-if-changed .
