name: Release Web
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"
          flutter-version: "3.10.0"
      - name: Build
        run: flutter build web --base-href /mdi/
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
